### ISSUE TITLE
Code for generating mesh

### ISSUE THREAD

**Issue by anhquancao** [OPEN-AIR-SUN/SISC#2]
Hello,

Thank you for a nice work!
I am trying to generate the mesh from SDF but I cannot get a clean mesh as in your visualizations.
Could you provide the code for generating the mesh?

Thank you very much,
Anh-Quan Cao

**Comment by anhquancao** [comment]
I found the problem!

**Comment by WkangLiu** [comment]
> Hello，I get the same problem too，can you tell me how to solve it ！
Thank you very much！
